include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters
    - prefer_const_declarations
    - unnecessary_lambdas
    - avoid_redundant_argument_values

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
