include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters
    - prefer_const_declarations
    - unnecessary_lambdas
    - avoid_redundant_argument_values
    - prefer_final_locals

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-raw-types: true

custom_lint:
  rules:
    - avoid_ref_inside_state_dispose
    - avoid_public_notifier_properties
    - missing_provider_scope
