name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "Release Version Name (e.g., 1.0.0)"
        required: true
      release_notes:
        description: "Release Notes (Markdown supported)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=my-release-key.keystore" >> android/key.properties

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi --build-number=${{ github.run_number }} -t lib/main.dart --dart-define=APP_VERSION=${{ github.event.inputs.version_name }}

      # iOS build steps (commented out for now - enable and configure when ready)
      # - name: Build iOS IPA
      #   run: |
      #     flutter build ios --release --no-codesign
      #     cd build/ios/iphoneos
      #     xcrun xcodebuild -archivePath Runner.xcarchive archive -scheme Runner -destination "generic/platform=iOS" # Add destination
      #     xcrun xcodebuild -exportArchive -archivePath Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ github.event.inputs.version_name }}
          name: Release v${{ github.event.inputs.version_name }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
          artifacts: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            # build/ios/iphoneos/Runner.ipa  # Add this back when you enable iOS builds
          generateReleaseNotes: true
